### ISSUE TITLE
[Issue] If "nudged", token's image begins to move in the direction of the nudge, eventually flying off screen. 

### ISSUE THREAD

**Issue by Vargock** [unsoluble/quickscale#12]
https://github.com/unsoluble/quickscale/assets/93734306/6695c1cc-d0fc-4158-b42f-5dc5a72a416a

- **Foundry:** v11.307;
- **QuickScale:** v1.6.4
- **Modules:** Tested with and without, the issue still persists;

When I attempt to "nudge" a token in any direction, the image begins to move in the direction of the nudge, seemingly applying the nudged distance again and again. The position is restored when a token is moved, but the floating images are incredibly distracting xD

The video example was filmed with modules enabled, but the result was the same when I tested it later without any.

**Comment by unsoluble** [comment]
Does this happen with _all_ tokens, in any scene? Does it happen in a new test world?

**Comment by Vargock** [comment]
Yes, with all tokens, any scene. Both PCs and NPCs, linked or not. Tested it on a new 5e world — same results.

**Comment by unsoluble** [comment]
And what exactly is the sequence of events here? Does this all happen on a single press of the assigned vertical nudge hotkey?

**Comment by Vargock** [comment]
> And what exactly is the sequence of events here? Does this all happen on a single press of the assigned vertical nudge hotkey?

1) I select a token, press the "nudge" hotkey (hold ALT + press ']' / '['), the token image nudges as expected.
2) When I let go of ALT or press it again, the token's image moves, in steps, vertically, as if the nudge that I applied to it earlier is added again and again. The same happens when I hover above the nudged token with a mouse, or when I drop new tokens to the scene, or when I press ALT again (so by pushing ALT an image moves twice, as if nudge value is applied twice in a row).
3) If a token is moved (WASD, for example), the image's position returns to normal (with nudge applied)

**Comment by unsoluble** [comment]
Mkay, thanks. I think I know what might be happening there, will take a look when I've got a chance. Fairly limited dev time available right now, but should be within the week.

**Comment by unsoluble** [comment]
Fixed in 1.6.5. Thanks for the heads-up on this one. :)
