### ISSUE TITLE
1.6.5 Causes all tokens to be severely off center

### ISSUE THREAD

**Issue by GambetTV** [unsoluble/quickscale#13]
All tokens now seem to center at the top of their bounding box square. There seems to be no setting to fix this.

![image](https://github.com/unsoluble/quickscale/assets/72000497/cd260eb8-1db6-4e12-8a08-e642cccb169f)

**Comment by unsoluble** [comment]
Oh. Hmm. Something has gone wrong there. Sec. :)

**Comment by unsoluble** [comment]
More complex than I can address right now, so reverting to the previous build. 1.6.6 should work for you.

**Comment by unsoluble** [comment]
Try 1.6.7 :)
