### ISSUE TITLE
changing shortcut keys

### ISSUE THREAD

**Issue by Darshyne** [unsoluble/quickscale#3]
Hello, would it be possible to change the shortcut keys via the V9 shortcut manager, because the bracket keys are not easily available on the azerty keyboards. :)

**Comment by unsoluble** [comment]
Yeah that's been on my to-do list since v9 came out, just haven't had the impetus to get around to it since nobody was asking. But now that you've asked... :)

I'll see if I can find some time in the next couple weeks to dig into that refactor.

**Comment by esheyw** [comment]
Just found this module, would very much like to be able to rebind the keys, consider this a +1 :)

**Comment by unsoluble** [comment]
Done in 1.4.0 :)
