### ISSUE TITLE
Error when dim < bright

### ISSUE THREAD

**Issue by JacksonBockus** [unsoluble/quickscale#6]
On a light, if dim radius < bright radius, then quickscale won't scale the bright radius down if the dim radius is equal to 0: it looks like it tries to set the dim radius to -1 and the bright radius to bright - 1, resulting in an invalid luminosity value (The error I get is that luminosity must be a finite number).

**Comment by unsoluble** [comment]
Yep, hadn't account for an inverted brightness setup like that. Fixed in 1.5.4.
