### ISSUE TITLE
[Feature Request] Token Dimensions quick scale

### ISSUE THREAD

**Issue by SirAron111** [unsoluble/quickscale#9]
Is there a way to adjust a tokens grid dimensions similarly? I have a rune knight fighter in my 5e game, and it would be way quicker to just have key binds to toggle him from medium to large (1withx1hight) to (2withx2hight) if the module could do something like this. Maybe an option to choose if it scales dimensions or grid hight and widh instead. Or maybe a button in the overlay or so to change a tokens size/dimensions? Something along these lines.

**Comment by unsoluble** [comment]
While it's certainly possible do make those changes programmatically, it's not something I'm going to implement in this module. If you pop into the #macro-polo channel on the discord, folks can help you with writing up a script.
